#!/usr/bin/env python3

import pathlib


def configure(cfg):
    extra_src_inc = [
        'libraries/AP_UROS/uros/include',
        'libraries/AP_UROS/uros/include/rcl',
        'libraries/AP_UROS/uros/include/rcl_action',
        'libraries/AP_UROS/uros/include/rcutils',
        'libraries/AP_UROS/uros/include/rmw',
        'libraries/AP_UROS/uros/include/rosidl_runtime_c',
        'libraries/AP_UROS/uros/include/rosidl_typesupport_interface',
        'libraries/AP_UROS/uros/include/rosidl_typesupport_introspection_c',
        'libraries/AP_UROS/uros/include/action_msgs',
        'libraries/AP_UROS/uros/include/ardupilot_msgs',
        'libraries/AP_UROS/uros/include/builtin_interfaces',
        'libraries/AP_UROS/uros/include/geographic_msgs',
        'libraries/AP_UROS/uros/include/geometry_msgs',
        'libraries/AP_UROS/uros/include/rosgraph_msgs',
        'libraries/AP_UROS/uros/include/sensor_msgs',
        'libraries/AP_UROS/uros/include/std_msgs',
        'libraries/AP_UROS/uros/include/tf2_msgs',
        'libraries/AP_UROS/uros/include/unique_identifier_msgs',
    ]
    for inc in extra_src_inc:
        cfg.env.INCLUDES += [str(cfg.srcnode.make_node(inc))]

    # Suppress build error:
    #
    # ../../libraries/AP_UROS/uros/include/rcutils/rcutils/error_handling.h:139:5:
    # fatal error: '__STDC_VERSION__' is not defined, evaluates to 0 [-Wundef]
    # #if __STDC_VERSION__ >= 201112L && !defined(RCUTILS_AVOID_DYNAMIC_ALLOCATION)
    #
    # Better to edit error_handling.h:139:5 ??
    # 
    # #if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L && !defined(RCUTILS_AVOID_DYNAMIC_ALLOCATION)
    # 
    cfg.env.AP_LIB_EXTRA_CXXFLAGS['AP_UROS'] = ['-Wno-undef']


def build(bld):
    bld.env.LIB += ['microros']
    bld.env.LIBPATH += [bld.env.SRCROOT + '/libraries/AP_UROS/uros/']
